### ISSUE TITLE
Task is not created with build.gradle.kts

### ISSUE THREAD

**Issue by quiro91** [davidburstrom/android-resource-namespacer#1]
Using AGP 4.0, Gradle 6.1, I don't see any task being created. The only meaningful difference compared to the project is that I use Kotlin for my build.gradle. After pasting the namespacer.gradle, I added the my root build.gradle.kts:
```
subprojects {
    if (hasProperty("android")) {
        apply(from = rootProject.file("namespacer.gradle"))
    }
}
```

Still if I run `./gradlew tasks | grep namespace` I see that no task has been created

**Comment by davidburstrom** [comment]
Thank you for the report! The project is only verified to work with AGP 3.6, so there may very well be an issue interacting with AGP 4.0. I'm not actively supporting the project, so any contributions are welcome.

**Comment by davidburstrom** [comment]
Though, are you sure that `hasProperty("android")` returns true?

**Comment by quiro91** [comment]
Hey, thanks for the answer! I've tried reverting it to AGP 3.6.0, I made sure the project was building after that, but still the plugin isn't applied. So I removed the `hasProperty("android")` (all my subprojects are android subprojects, so that shouldn't really be an issue) and I've added the `afterEvaluate` block. So now the code looks like:

```
subprojects {
    afterEvaluate {
        apply(from = rootProject.file("namespacer.gradle"))
    }
}
```

The result though is:

```
Caused by: com.android.build.gradle.internal.crash.ExternalApiUsageException: org.gradle.api.InvalidActionClosureException: The closure 'namespacer_et3thfjz0aeinewfg6jdr26a9$_run_closure1@3aa659a2' is not valid as an action for argument 'com.android.build.gradle.internal.api.LibraryVariantImpl_Decorated@53b2a911'. It should accept no parameters, or one compatible with type 'com.android.build.gradle.internal.api.LibraryVariantImpl_Decorated'. It accepts (com.android.build.gradle.api.BaseVariant).
```

This is happening in the first alphabetical module of the project, which has the "com.android.library" plugin applied. Any idea why this could be happening?

**Comment by davidburstrom** [comment]
Do you get that error message with AGP 3.6.0 or AGP 4.0.0?

**Comment by quiro91** [comment]
AGP 3.6.0

**Comment by arlindiDev** [comment]
Any update on this?
